# Generated by Django 4.2.3 on 2023-10-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa', '0007_alter_parkings_latitude_alter_parkings_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkings',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkings',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
